### ISSUE TITLE
Random.normal using :f16 sometimes generates -Inf

### ISSUE THREAD

**Issue by meanderingstream** [elixir-nx/nx#981] opened 2022-11-11 21:16 UTC
I've found that Random.normal with a mean of 0 and standard deviation of 3.0 or 5.0 results in Inf numbers when generating :f16 numbers. Taking the mean of a tensor helps identify when there is a -Inf or Inf number in the tensor. 

Using Nx version 4.0 with BinaryBackend, the following can repeat this issue.

rndm_key = Nx.Random.key(52)
{samples, _} =
  Nx.Random.normal(rndm_key, 0, 3.0, shape: {1500}, type: :f16)
Nx.mean(samples)

**Comment by josevalim** [comment] 2022-11-13 10:17
I was able to isolate it a bit further:

```
rndm_key = Nx.Random.key(52)
min_value = Nx.subtract(Nx.Constants.smallest_positive_normal({:f, 16}), 1)
{samples, _} = Nx.Random.uniform(rndm_key, min_value, 1, shape: {1500}, type: :f16)
IO.inspect samples
post = Nx.erf_inv(samples)
IO.inspect Nx.mean(post)
result = Nx.select(Nx.equal(post, Nx.Constants.neg_infinity()), samples, 0)
IO.inspect Nx.to_flat_list(result) |> Enum.reject(& &1 == 0.0)
```

`normal` is implemented on top of uniform. Then it performs a `erf_inv` operation, which returns negative infinity. By executing the above, you can see the error happens because we compute the `erf_inv` of `-1.0` (which returns `neg_infinity`).

I need to explore more the boundaries given to `uniform`, as that may be the root cause.

**Comment by josevalim** [comment] 2022-11-13 10:22
Ok, here is the issue:

```
min_value = Nx.subtract(Nx.Constants.smallest_positive_normal({:f, 16}), 1)
IO.inspect Nx.Constants.smallest_positive_normal({:f, 16})
IO.inspect min_value
```

That is returning `-1`. Because:

```
iex(1)> Nx.as_type(6.103515625e-5 - 1, :f16)
#Nx.Tensor<
  f16
  -1.0
>
```

We don't actually have f16 computations in the binary backend, we upscale to f64 and then downscale, and that's what is causing the issue here.

**Comment by josevalim** [comment] 2022-11-13 10:39
Nevermind, the error also happens in other backends.

**Comment by josevalim** [comment] 2022-11-13 10:42
The way JAX handles this is by calling `np.nextafter`, to make sure the next value is within the given precision.

**Comment by josevalim** [comment] 2022-11-13 11:28
I have pushed a fix. I could use `eps` but to make sure there are no precision issues, I chose to do a bit manipulation and decrease the precision by one.

**Closed** 2022-11-13 11:27 UTC
