### ISSUE TITLE
Can't build TorchX for Mac M1

### ISSUE THREAD

**Issue by av-ast** [elixir-nx/nx#593] opened 2021-12-22 13:43 UTC
I'm trying to build NX in docker container on my Macbook Air M1 and get an error.
```
#7 89.63 [100%] Linking CXX executable torchx.so
#7 89.64 /usr/bin/ld: ../../../../../cache/libtorch-1.9.1-cpu/lib/libtorch.so: error adding symbols: file in wrong format
#7 89.64 collect2: error: ld returned 1 exit status
``` 

Here is my Dockerfile

```Dockerfile
FROM elixir:latest

RUN apt update \
    && apt install -y build-essential cmake

RUN mix local.hex --force && \
    mix local.rebar --force

RUN mkdir /nx

RUN git clone https://github.com/elixir-nx/nx.git /nx \
    && cd /nx && make
```

Here is the full output
```
λ docker build .

[+] Building 91.1s (8/8) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                     0.9s
 => => transferring dockerfile: 450B                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                        0.6s
 => => transferring context: 2B                                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/elixir:latest                                                                                         0.0s
 => [1/5] FROM docker.io/library/elixir:latest                                                                                                           0.0s
 => CACHED [2/5] RUN apt update     && apt install -y build-essential cmake                                                                              0.0s
 => CACHED [3/5] RUN mix local.hex --force &&     mix local.rebar --force                                                                                0.0s
 => CACHED [4/5] RUN mkdir /nx                                                                                                                           0.0s
 => ERROR [5/5] RUN git clone https://github.com/elixir-nx/nx.git /nx     && cd /nx && make                                                             90.1s
------
 > [5/5] RUN git clone https://github.com/elixir-nx/nx.git /nx     && cd /nx && make:
#7 0.721 Cloning into '/nx'...
#7 5.034 Resolving Hex dependencies...
#7 5.040 Dependency resolution completed:
#7 5.040 Unchanged:
#7 5.040   earmark_parser 1.4.12
#7 5.040   ex_doc 0.23.0
#7 5.040   makeup 1.0.5
#7 5.040   makeup_elixir 0.15.1
#7 5.040   nimble_parsec 1.1.0
#7 5.049 * Getting ex_doc (Hex package)
#7 5.327 * Getting earmark_parser (Hex package)
#7 5.336 * Getting makeup_elixir (Hex package)
#7 5.341 * Getting makeup (Hex package)
#7 5.369 * Getting nimble_parsec (Hex package)
#7 6.104 Resolving Hex dependencies...
#7 6.109 Dependency resolution completed:
#7 6.109 Unchanged:
#7 6.109   benchee 1.0.1
#7 6.109   deep_merge 1.0.0
#7 6.109   earmark_parser 1.4.12
#7 6.109   elixir_make 0.6.2
#7 6.109   ex_doc 0.23.0
#7 6.109   makeup 1.0.5
#7 6.109   makeup_elixir 0.15.1
#7 6.109   nimble_parsec 1.1.0
#7 6.109   xla 0.2.0
#7 6.121 * Getting xla (Hex package)
#7 6.217 * Getting elixir_make (Hex package)
#7 6.221 * Getting benchee (Hex package)
#7 6.283 * Getting ex_doc (Hex package)
#7 6.303 * Getting earmark_parser (Hex package)
#7 6.312 * Getting makeup_elixir (Hex package)
#7 6.316 * Getting makeup (Hex package)
#7 6.326 * Getting nimble_parsec (Hex package)
#7 6.329 * Getting deep_merge (Hex package)
#7 6.950 Resolving Hex dependencies...
#7 6.954 Dependency resolution completed:
#7 6.954 Unchanged:
#7 6.954   earmark_parser 1.4.12
#7 6.954   elixir_make 0.6.2
#7 6.954   ex_doc 0.23.0
#7 6.954   makeup 1.0.5
#7 6.954   makeup_elixir 0.15.1
#7 6.954   nimble_parsec 1.1.0
#7 6.963 * Getting elixir_make (Hex package)
#7 6.983 * Getting ex_doc (Hex package)
#7 7.007 * Getting earmark_parser (Hex package)
#7 7.029 * Getting makeup_elixir (Hex package)
#7 7.033 * Getting makeup (Hex package)
#7 7.050 * Getting nimble_parsec (Hex package)
#7 7.321 ==> earmark_parser
#7 7.321 Compiling 1 file (.yrl)
#7 7.337 Compiling 2 files (.xrl)
#7 7.358 Compiling 3 files (.erl)
#7 7.470 Compiling 32 files (.ex)
#7 8.226 Generated earmark_parser app
#7 8.238 ==> nimble_parsec
#7 8.238 Compiling 4 files (.ex)
#7 8.545 Generated nimble_parsec app
#7 8.568 ==> makeup
#7 8.568 Compiling 44 files (.ex)
#7 9.040 Generated makeup app
#7 9.061 ==> makeup_elixir
#7 9.061 Compiling 6 files (.ex)
#7 13.34 Generated makeup_elixir app
#7 13.36 ==> ex_doc
#7 13.36 Compiling 22 files (.ex)
#7 13.97 Generated ex_doc app
#7 13.98 ==> nx
#7 13.98 Compiling 23 files (.ex)
#7 17.48 Generated nx app
#7 17.87 ==> earmark_parser
#7 17.87 Compiling 1 file (.yrl)
#7 17.88 Compiling 2 files (.xrl)
#7 17.90 Compiling 3 files (.erl)
#7 18.02 Compiling 32 files (.ex)
#7 18.75 Generated earmark_parser app
#7 18.76 ==> nimble_parsec
#7 18.76 Compiling 4 files (.ex)
#7 19.06 Generated nimble_parsec app
#7 19.08 ==> makeup
#7 19.08 Compiling 44 files (.ex)
#7 19.52 Generated makeup app
#7 19.54 ==> deep_merge
#7 19.54 Compiling 2 files (.ex)
#7 19.68 Generated deep_merge app
#7 19.71 ==> benchee
#7 19.71 Compiling 39 files (.ex)
#7 20.16 Generated benchee app
#7 20.17 ==> nx
#7 20.17 Compiling 23 files (.ex)
#7 23.71 Generated nx app
#7 23.72 ==> elixir_make
#7 23.72 Compiling 1 file (.ex)
#7 23.81 Generated elixir_make app
#7 23.83 ==> xla
#7 23.83 Compiling 2 files (.ex)
#7 23.93 Generated xla app
#7 23.95 ==> makeup_elixir
#7 23.95 Compiling 6 files (.ex)
#7 28.22 Generated makeup_elixir app
#7 28.23 ==> ex_doc
#7 28.23 Compiling 22 files (.ex)
#7 28.87 Generated ex_doc app
#7 29.53
#7 29.53 12:45:47.120 [info]  Found a matching archive (xla_extension-aarch64-linux-cpu.tar.gz), going to download it
#7 29.55   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#7 29.55                                  Dload  Upload   Total   Spent    Left  Speed
100   677  100   677    0     0   1776      0 --:--:-- --:--:-- --:--:--  1776
100 78.7M  100 78.7M    0     0  12.9M      0  0:00:06  0:00:06 --:--:-- 17.7M
#7 35.64
#7 35.64 12:45:53.236 [info]  Successfully downloaded the XLA archive
#7 35.64 ==> exla
#7 35.64 Unpacking /root/.cache/xla/0.2.0/cache/download/xla_extension-aarch64-linux-cpu.tar.gz into /nx/exla/cache
#7 38.81 make[1]: Entering directory '/nx/exla'
#7 38.81 mkdir -p /nx/exla/_build/dev/lib/exla/priv
#7 38.81 ln -sf /nx/exla/cache/xla_extension/lib /nx/exla/_build/dev/lib/exla/priv/lib
#7 38.82 g++ -fPIC -I/usr/local/lib/erlang/erts-12.2/include -isystem cache/xla_extension/include -O3 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-comment -shared -std=c++14 c_src/exla/exla.cc c_src/exla/exla_nif_util.cc c_src/exla/exla_client.cc -o /nx/exla/_build/dev/lib/exla/priv/libexla.so -L/nx/exla/_build/dev/lib/exla/priv/lib -lxla_extension -Wl,-rpath,'$ORIGIN/lib'
#7 53.88 make[1]: Leaving directory '/nx/exla'
#7 53.88 Compiling 21 files (.ex)
#7 54.72 Generated exla app
#7 55.15 ==> earmark_parser
#7 55.15 Compiling 1 file (.yrl)
#7 55.17 Compiling 2 files (.xrl)
#7 55.19 Compiling 3 files (.erl)
#7 55.30 Compiling 32 files (.ex)
#7 56.08 Generated earmark_parser app
#7 56.09 ==> nimble_parsec
#7 56.09 Compiling 4 files (.ex)
#7 56.39 Generated nimble_parsec app
#7 56.41 ==> makeup
#7 56.41 Compiling 44 files (.ex)
#7 56.87 Generated makeup app
#7 56.88 ==> nx
#7 56.88 Compiling 23 files (.ex)
#7 60.41 Generated nx app
#7 60.42 ==> elixir_make
#7 60.42 Compiling 1 file (.ex)
#7 60.51 Generated elixir_make app
#7 60.54 ==> makeup_elixir
#7 60.54 Compiling 6 files (.ex)
#7 64.84 Generated makeup_elixir app
#7 64.85 ==> ex_doc
#7 64.85 Compiling 22 files (.ex)
#7 65.48 Generated ex_doc app
#7 65.49   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#7 65.49                                  Dload  Upload   Total   Spent    Left  Speed
100  185M  100  185M    0     0  16.7M      0  0:00:11  0:00:11 --:--:-- 17.3M
#7 81.59 ==> torchx
#7 81.60 make[1]: Entering directory '/nx/torchx'
#7 81.64 -- The C compiler identification is GNU 10.2.1
#7 81.68 -- The CXX compiler identification is GNU 10.2.1
#7 81.68 -- Detecting C compiler ABI info
#7 81.72 -- Detecting C compiler ABI info - done
#7 81.73 -- Check for working C compiler: /usr/bin/cc - skipped
#7 81.73 -- Detecting C compile features
#7 81.73 -- Detecting C compile features - done
#7 81.73 -- Detecting CXX compiler ABI info
#7 81.78 -- Detecting CXX compiler ABI info - done
#7 81.78 -- Check for working CXX compiler: /usr/bin/c++ - skipped
#7 81.78 -- Detecting CXX compile features
#7 81.78 -- Detecting CXX compile features - done
#7 81.79 -- Looking for pthread.h
#7 81.83 -- Looking for pthread.h - found
#7 81.83 -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
#7 81.87 -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
#7 81.87 -- Looking for pthread_create in pthreads
#7 81.90 -- Looking for pthread_create in pthreads - not found
#7 81.90 -- Looking for pthread_create in pthread
#7 81.95 -- Looking for pthread_create in pthread - found
#7 81.95 -- Found Threads: TRUE
#7 81.95 -- Found Torch: /nx/torchx/cache/libtorch-1.9.1-cpu/lib/libtorch.so
#7 81.95 -- Configuring done
#7 81.96 -- Generating done
#7 81.96 -- Build files have been written to: /nx/torchx/_build/dev/lib/torchx/cmake
#7 81.96 gmake[2]: Entering directory '/nx/torchx/_build/dev/lib/torchx/cmake'
#7 81.98 gmake[3]: Entering directory '/nx/torchx/_build/dev/lib/torchx/cmake'
#7 81.98 gmake[4]: Entering directory '/nx/torchx/_build/dev/lib/torchx/cmake'
#7 82.00 Scanning dependencies of target torchx.so
#7 82.00 gmake[4]: Leaving directory '/nx/torchx/_build/dev/lib/torchx/cmake'
#7 82.00 gmake[4]: Entering directory '/nx/torchx/_build/dev/lib/torchx/cmake'
#7 82.01 [ 50%] Building CXX object CMakeFiles/torchx.so.dir/c_src/torchx.cpp.o
#7 89.63 [100%] Linking CXX executable torchx.so
#7 89.64 /usr/bin/ld: ../../../../../cache/libtorch-1.9.1-cpu/lib/libtorch.so: error adding symbols: file in wrong format
#7 89.64 collect2: error: ld returned 1 exit status
#7 89.64 gmake[4]: *** [CMakeFiles/torchx.so.dir/build.make:107: torchx.so] Error 1
#7 89.64 gmake[4]: Leaving directory '/nx/torchx/_build/dev/lib/torchx/cmake'
#7 89.64 gmake[3]: *** [CMakeFiles/Makefile2:95: CMakeFiles/torchx.so.dir/all] Error 2
#7 89.64 gmake[3]: Leaving directory '/nx/torchx/_build/dev/lib/torchx/cmake'
#7 89.64 gmake[2]: *** [Makefile:103: all] Error 2
#7 89.64 gmake[2]: Leaving directory '/nx/torchx/_build/dev/lib/torchx/cmake'
#7 89.64 make[1]: *** [Makefile:29: /nx/torchx/_build/dev/lib/torchx/priv/torchx.so] Error 2
#7 89.64 make[1]: Leaving directory '/nx/torchx'
#7 89.64 ** (Mix) Could not compile with "make" (exit status: 2).
#7 89.64 You need to have gcc and make installed. If you are using
#7 89.64 Ubuntu or any other Debian-based system, install the packages
#7 89.64 "build-essential". Also install "erlang-dev" package if not
#7 89.64 included in your Erlang/OTP version. If you're on Fedora, run
#7 89.64 "dnf group install 'Development Tools'".
#7 89.64
#7 89.69 make: *** [Makefile:4: all] Error 1
------
executor failed running [/bin/sh -c git clone https://github.com/elixir-nx/nx.git /nx     && cd /nx && make]: exit code: 2
```

**Comment by av-ast** [comment] 2021-12-22 13:45
As I understand, the reason is libtorch library which is built for x86, right? https://github.com/elixir-nx/nx/blob/main/torchx/mix.exs#L102

**Comment by polvalente** [comment] 2021-12-22 13:45
@av-ast Have you tried downloading libtorch manually and setting LIBTORCH_DIR with the correct version for M1?
I suspect that the problem is that the autodownload if for non-M1 architecture

**Comment by polvalente** [comment] 2021-12-22 13:47
> As I understand, the reason is libtorch library which is built for x86, right? https://github.com/elixir-nx/nx/blob/main/torchx/mix.exs#L102

Yes, this is probably the root cause. As I said in the other comment, you can download/build your own libtorch build and then you point to it through LIBTORCH_DIR, which will skip the autodownload

**Comment by av-ast** [comment] 2021-12-22 13:52
@polvalente From the README I followed this page https://pytorch.org/get-started/locally/ but I see no option to get the proper download link. Could you please point me?

**Comment by av-ast** [comment] 2021-12-22 13:55
Looks like the only option is to build libtorch from the source code?

**Comment by polvalente** [comment] 2021-12-22 13:55
@av-ast From this StackOverflow answer (https://stackoverflow.com/questions/65593177/how-to-build-libtorch-on-mac-arm), it seems that you indeed need to build from source

**Comment by polvalente** [comment] 2021-12-22 13:56
Please try this out and let us know if it works! If it does, we can update the README accordingly!

**Comment by av-ast** [comment] 2021-12-28 10:27
@polvalente that StackOverflow solution does work. 

I've wrapped it into a Docker image here https://github.com/av-ast/nx-docker

**Comment by josevalim** [comment] 2021-12-28 12:13
Thank you for reporting back! I will add a reference to the README to this issue and close it.

**Closed by josevalim** 2021-12-28 12:13 UTC
