### ISSUE TITLE
Nx.as_type/2 loses precision on constants

### ISSUE THREAD

**Issue by woodward** [elixir-nx/nx#1224] opened 2023-05-22 20:30 UTC
Hi:

Here's an example which shows a loss of precision which seems a little surprising to me when using `Nx.as_type/2`:

```
iex(2)> Nx.as_type(0.38, :f64) |> IO.inspect()
#Nx.Tensor<
  f64
  0.3799999952316284
>
```

whereas `Nx.tensor/2` does the following (which is correct for :f64):

```
iex(3)> Nx.tensor(0.38, type: :f64) |> IO.inspect()
#Nx.Tensor<
  f64
  0.38
>
```

Thank you for any help you can provide!

-- Greg

**Comment by josevalim** [comment] 2023-05-22 22:06
Duplicate of #448. :)

**Comment by josevalim** [comment] 2023-05-22 22:22
I was wrong, not a dup. :)

**Closed** 2023-05-22 23:22 UTC
